// 目标任务协议：Task / Run 分离、计划投影步骤、Workflow 脚本运行记录、集中事件目录与稳定错误码族。
// Goal-task protocol: Task/Run separation, plan-projection steps, workflow script run records, centralized event catalog, stable error codes.
//
// 设计约束（对应计划 §5、§11.3、§11.4、§13.1、§14.8、§14.9、§14.11）：
// - Task 管目标层终态，TaskRun 管单次执行过程态；retry 只创建新 Run。
// - 本模块只做协议，不引入第二套状态机实现；通用状态机资产在
//   packages/protocol/src/taskStateMachine.ts（并行改造中）中抽取，本文件不 import 它。
// - 不把 UI 结构放进 protocol。
import { z } from 'zod';
import type { GoalEvaluation } from './types.js';

// ─── Task 状态（目标层） ─────────────────────────────────────────────────────
// Task status (goal layer).

/** Task 的目标层完整状态集合。/ Full goal-layer status set of a Task. */
export const TASK_STATUSES = [
  'pending',
  'running',
  'blocked',
  'completed',
  'failed',
  'cancelled',
] as const;

export type TaskStatus = (typeof TASK_STATUSES)[number];

/**
 * Task 状态机的唯一允许迁移表。终态（completed / cancelled / failed）故意没有任何出口。
 * The single allowed transition table for Task status. Terminal states intentionally have no exits.
 */
export const TASK_STATUS_TRANSITIONS: Readonly<Record<TaskStatus, readonly TaskStatus[]>> = {
  pending: ['running', 'blocked', 'cancelled', 'failed'],
  running: ['blocked', 'completed', 'failed', 'cancelled'],
  blocked: ['running', 'cancelled', 'failed'],
  completed: [],
  cancelled: [],
  failed: [],
};

export const TASK_STATUS_TERMINAL_STATES: ReadonlySet<TaskStatus> = new Set([
  'completed',
  'cancelled',
  'failed',
]);

export function isTaskStatus(value: string): value is TaskStatus {
  return (TASK_STATUSES as readonly string[]).includes(value);
}

/** 判断 Task 是否处于终态（不可再迁移，只能通过新 Run/新 Task 继续）。 */
/** Whether a Task status is terminal (only a new Run or new Task may continue). */
export function isTaskTerminalState(status: TaskStatus): boolean {
  return TASK_STATUS_TERMINAL_STATES.has(status);
}

export function canTransitionTaskStatus(from: TaskStatus, to: TaskStatus): boolean {
  return TASK_STATUS_TRANSITIONS[from].includes(to);
}

export const TASK_STATUS_TRANSITION_MAP = TASK_STATUS_TRANSITIONS;
export const TASK_STATUS_TERMINAL_STATE_SET = TASK_STATUS_TERMINAL_STATES;

// ─── Run 分类 ────────────────────────────────────────────────────────────────
// Run classification.

/** Run 的大类：GoalRun（目标续跑）或 WorkflowRun（并行编排）。 */
/** Run kind: GoalRun (continuation) or WorkflowRun (parallel orchestration). */
export const TASK_RUN_KINDS = ['goal', 'workflow'] as const;
export type TaskRunKind = (typeof TASK_RUN_KINDS)[number];

/**
 * Workflow 子类型（计划 §14.8）。TaskRunKind 只区分 GoalRun / WorkflowRun，
 * 不承担 Blueprint 与 Script 的语义；数据层必须可区分二者。
 * Workflow subtype: Blueprint (visual static graph) vs Script (restricted JS generated by the model).
 */
export const WORKFLOW_KINDS = ['blueprint', 'script'] as const;
export type WorkflowKind = (typeof WORKFLOW_KINDS)[number];

/**
 * 交互模式协议占位（计划 §14.11）。第一版默认 `supervised`，不实现三套完整执行策略；
 * 仅作为协议字段预留，服务端不得依据它放宽权限或跳过批准。
 * Interaction-mode protocol placeholder. First version always behaves as `supervised`;
 * the other modes are reserved and must not relax permissions.
 */
export const TASK_INTERACTION_MODES = ['autonomous', 'interactive', 'supervised'] as const;
export type TaskInteractionMode = (typeof TASK_INTERACTION_MODES)[number];

/**
 * Task 的来源。`explicit_goal` 是用户明确创建的 Goal，`explicit_workflow` 是用户明确
 * 创建的 Script Workflow；`harness_shadow` 是普通 Agent/Harness 的内部运行镜像，不能作为
 * Goal 或 Dynamic Workflow 的入口。历史记录缺失该字段时一律按 `harness_shadow` 处理。
 */
export const TASK_ORIGINS = ['explicit_goal', 'explicit_workflow', 'harness_shadow'] as const;
export type TaskOrigin = (typeof TASK_ORIGINS)[number];

/** Task 是用户可见的一等任务实体：只表达目标层，不表达执行过程态。 */
/** A Task is the user-visible first-class entity: goal layer only, never process state. */
export interface Task {
  id: string;
  threadId: string;
  objective: string;
  acceptanceCriteria: string[];
  status: TaskStatus;
  /** 当前活跃 Run；一个 Thread 同一时刻最多一个 active Task。 */
  /** Current active run id; at most one active Task per thread. */
  currentRunId?: string;
  /** 历史 Run 顺序集合；retry 追加新 Run，不复活旧 Run。 */
  /** Ordered run ids; retry appends a new run instead of reviving an old one. */
  runIds: string[];
  /** 最新计划版本投影（只读投影，不作为第二执行引擎）。 */
  latestPlan?: TaskPlanVersion;
  evidenceIds: string[];
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
  /** blocked 时展示的结构化待处理问题。 */
  pendingInput?: PendingUserInput;
  /** 乐观锁版本；每次成功状态迁移递增，初始为 0。/ Optimistic-lock version, starting at 0. */
  version: number;
  /** 协议占位：第一版默认 supervised。/ Reserved: defaults to supervised in v1. */
  interactionMode?: TaskInteractionMode;
  /**
   * 创建来源。字段缺失只可能来自旧数据，读取时必须等同于 `harness_shadow`。
   * Provenance is immutable after creation; absent legacy data is a Harness shadow.
   */
  origin?: TaskOrigin;
}

// ─── TaskRun 过程态 ──────────────────────────────────────────────────────────
// TaskRun process state.

/** TaskRun 的过程态集合。/ Full process-state set of a TaskRun. */
export const TASK_RUN_STATES = [
  'queued',
  'running',
  'paused',
  'blocked',
  'completed',
  'failed',
  'cancelled',
  'interrupted',
] as const;

export type TaskRunState = (typeof TASK_RUN_STATES)[number];

/**
 * TaskRun 状态机的唯一迁移表（计划 §11.4）。禁止在实现层用散落 if/else 另起一套迁移规则。
 * The single TaskRun transition table; implementations must not rely on scattered if/else rules.
 *
 * 补充语义：
 * - `blocked -> queued` 表示等待用户输入后重新排队。
 * - `interrupted` 恢复前必须核对 Agent Checkpoint。
 * - 终态无出口；`retry` 只创建新 Run，不修改旧 Run 终态。
 *
 * 对 §11.4 原表的必要补边（计划表只列了出口，未给 completed / interrupted 任何入口，
 * 会使 GoalRun 成功落终态与 §11.2 恢复扫描标记 interrupted 两条合法路径无法表达）：
 * - `running -> completed`：执行成功且验收通过后由上层（P3 GoalEvaluator gate）落入。
 * - `queued|running|paused|blocked -> interrupted`：崩溃/重启恢复扫描的 system-only 迁移，
 *   调用方必须先核对 Agent Checkpoint 才能写入（§11.2）。
 */
export const TASK_RUN_TRANSITIONS: Readonly<Record<TaskRunState, readonly TaskRunState[]>> = {
  queued: ['running', 'blocked', 'cancelled', 'failed', 'interrupted'],
  running: ['paused', 'blocked', 'cancelled', 'failed', 'completed', 'interrupted'],
  paused: ['running', 'cancelled', 'failed', 'interrupted'],
  blocked: ['queued', 'cancelled', 'failed', 'interrupted'],
  interrupted: ['running', 'queued', 'cancelled', 'failed'],
  completed: [],
  cancelled: [],
  failed: [],
};

export const TASK_RUN_TERMINAL_STATES: ReadonlySet<TaskRunState> = new Set([
  'completed',
  'cancelled',
  'failed',
]);

// 与 OpsTask 资产保持同构的别名集合，便于通用状态机模块后续接管。
// Aliases mirroring the OpsTask asset names so the shared state-machine module can take over later.
export const TASK_RUN_TRANSITION_MAP = TASK_RUN_TRANSITIONS;
export const TASK_RUN_TERMINAL_STATE_SET = TASK_RUN_TERMINAL_STATES;

export function isTaskRunState(value: string): value is TaskRunState {
  return (TASK_RUN_STATES as readonly string[]).includes(value);
}

export function isTaskRunTerminalState(state: TaskRunState): boolean {
  return TASK_RUN_TERMINAL_STATES.has(state);
}

export function canTransitionTaskRun(from: TaskRunState, to: TaskRunState): boolean {
  return TASK_RUN_TRANSITIONS[from].includes(to);
}

export const isValidTaskRunTransition = canTransitionTaskRun;

/** TaskRun 的过程态承载实体。/ A single execution attempt of a Task. */
export interface TaskRun {
  id: string;
  taskId: string;
  threadId: string;
  kind: TaskRunKind;
  status: TaskRunState;
  /** kind='goal' 时关联既有 Harness run id。 */
  harnessRunId?: string;
  /** kind='workflow' 时关联 WorkflowRunRecord id。 */
  workflowRunId?: string;
  /** kind='workflow' 时的子类型；kind='goal' 时必须缺省。 */
  /** Workflow subtype; only meaningful when kind === 'workflow'. */
  workflowKind?: WorkflowKind;
  startedAt?: string;
  updatedAt: string;
  completedAt?: string;
  error?: string;
  /**
   * 指向现有 Agent Checkpoint（packages/protocol/src/types.ts 的 `Checkpoint`）的标识。
   * 恢复真相只存在于 Agent Checkpoint，禁止在 Task 表与 Checkpoint 之间各写一份恢复机制。
   * 恢复顺序：读 task_runs.checkpointId → 读 Agent Checkpoint → 按 executionStatus/decisionRequest
   * 决定 resume / 继续停止 / 还原 pending decision / 落终态 / 标记 interrupted → 回写 task_runs。
   *
   * References the existing Agent `Checkpoint` in ./types.js. It is NOT a new recovery mechanism:
   * the Agent Checkpoint stays the single source of resume truth, and task_runs only mirrors it.
   */
  checkpointId?: string;
  /** 乐观锁版本；每次成功迁移递增。/ Optimistic-lock version, incremented per transition. */
  version: number;
}

// ─── 计划投影与步骤状态 ──────────────────────────────────────────────────────
// Plan projection and step statuses.

/**
 * TaskStep 六态集合。HarnessPlanNode 保持既有四态，不扩成六态；
 * 六态只存在于展示层与验收层，由 planProjection 派生。
 *
 * 计划 §14.2 映射表 / mapping from HarnessPlanNode.status:
 *
 * | HarnessPlanNode.status | Evidence 结果                              | TaskStep.status |
 * |------------------------|--------------------------------------------|-----------------|
 * | pending                | -                                          | pending         |
 * | in_progress            | -                                          | in_progress     |
 * | completed              | evidenceIds 非空且 Evidence 有效           | verified        |
 * | completed              | 无证据或 Evidence 无效                     | claimed         |
 * | failed                 | -                                          | failed          |
 * | -                      | 用户或系统显式跳过                          | skipped         |
 *
 * 规则：模型声明 completed 时投影层不得直接写 verified；claimed 可显示但不可验收；
 * skipped 不得由模型用来绕过验收，必须由用户 redirect 或明确策略触发。
 */
export const TASK_STEP_STATUSES = [
  'pending',
  'in_progress',
  'claimed',
  'verified',
  'failed',
  'skipped',
] as const;

export type TaskStepStatus = (typeof TASK_STEP_STATUSES)[number];

/** 可显示但不可验收的状态集合（模型自述完成、缺有效证据）。 */
/** Statuses that may be displayed but never satisfy acceptance criteria. */
export const TASK_STEP_NON_ACCEPTABLE_STATUSES: readonly TaskStepStatus[] = ['claimed'];

export function isTaskStepStatus(value: string): value is TaskStepStatus {
  return (TASK_STEP_STATUSES as readonly string[]).includes(value);
}

/** 计划中的单个步骤投影。/ One projected plan step. */
export interface TaskStep {
  /**
   * 系统分配的稳定 id；模型不能生成或修改。模型输出新计划时，已有步骤只能通过 id 引用，
   * 新步骤不携带 id，由投影层补发。
   * System-assigned stable id; the model may neither generate nor modify it. New steps come without
   * an id and are assigned by planProjection.
   */
  id: string;
  description: string;
  status: TaskStepStatus;
  /** 支撑该步骤的证据 id 集合；verified 要求其中至少存在一条有效 Evidence。 */
  evidenceIds: string[];
  dependsOn?: string[];
  failureReason?: string;
  startedAt?: string;
  completedAt?: string;
}

/** 计划版本触发来源。/ What caused a new plan version to be recorded. */
export const TASK_PLAN_TRIGGERS = ['init', 'replan', 'redirect', 'failure'] as const;
export type TaskPlanTrigger = (typeof TASK_PLAN_TRIGGERS)[number];

/** 一次计划快照的版本化记录。/ Versioned record of one plan snapshot. */
export interface TaskPlanVersion {
  version: number;
  createdAt: string;
  trigger: TaskPlanTrigger;
  steps: TaskStep[];
}

/** 任务 blocked 时向用户提出的结构化问题（计划 §5.3）。本地单用户场景不做超时自动推进。 */
/** Structured question surfaced while a task is blocked; no timeout auto-advance locally. */
export interface PendingUserInput {
  question: string;
  options?: string[];
  /** 是否允许自由文本回复。/ Whether free-text answers are accepted. */
  freeText: boolean;
  askedAt: string;
}

/** replan 预算与冷却策略，防止计划震荡循环（计划 §5.2）。 */
/** Replan budget/cooldown policy preventing plan thrashing. */
export interface ReplanPolicy {
  maxReplansPerTask: number;
  minIntervalMs: number;
  triggerThreshold: number;
  tokenBudget: number;
}

/**
 * Goal 预算治理（计划 §14.11）。`maxWorkflowRunsPerGoal` 与 `ReplanPolicy` 并列，
 * 防止 Goal 无限触发大规模 Workflow。
 * Goal budget governance; maxWorkflowRunsPerGoal caps how often a Goal may trigger big workflows.
 */
export interface GoalBudgetPolicy {
  maxContinuations: number;
  maxNoProgress: number;
  maxWorkflowRunsPerGoal: number;
  replan: ReplanPolicy;
}

/** 默认 replan 策略。/ Default replan policy. */
export const DEFAULT_REPLAN_POLICY: Readonly<ReplanPolicy> = {
  maxReplansPerTask: 3,
  minIntervalMs: 30_000,
  triggerThreshold: 2,
  tokenBudget: 200_000,
};

/** 默认 Goal 预算策略（计划值：与 DEFAULT_REPLAN_POLICY 并列）。 */
/** Default goal budget policy. */
export const DEFAULT_GOAL_BUDGET_POLICY: Readonly<GoalBudgetPolicy> = {
  maxContinuations: 8,
  maxNoProgress: 3,
  maxWorkflowRunsPerGoal: 2,
  replan: DEFAULT_REPLAN_POLICY,
};

// ─── Workflow 脚本运行时 ─────────────────────────────────────────────────────
// Workflow script runtime.

/** WorkflowRun 的状态集合（含 §11.4 的 interrupted 语义）。 */
/** Status set of a workflow run. */
export const WORKFLOW_RUN_STATUSES = [
  'queued',
  'running',
  'paused',
  'blocked',
  'completed',
  'failed',
  'cancelled',
  'interrupted',
] as const;

export type WorkflowRunStatus = (typeof WORKFLOW_RUN_STATUSES)[number];

export const WORKFLOW_RUN_TERMINAL_STATUSES: ReadonlySet<WorkflowRunStatus> = new Set([
  'completed',
  'failed',
  'cancelled',
]);

export function isWorkflowRunStatus(value: string): value is WorkflowRunStatus {
  return (WORKFLOW_RUN_STATUSES as readonly string[]).includes(value);
}

export function isWorkflowRunTerminalStatus(status: WorkflowRunStatus): boolean {
  return WORKFLOW_RUN_TERMINAL_STATUSES.has(status);
}

/** 单次 WorkflowRun 的资源消耗统计。/ Accumulated usage of one workflow run. */
export interface WorkflowUsage {
  inputTokens: number;
  outputTokens: number;
  agentCallCount: number;
  durationMs: number;
}

/** WorkflowAgentCall 的状态集合。/ Status set of a single agent() call inside a script. */
export const WORKFLOW_AGENT_CALL_STATUSES = [
  'pending',
  'running',
  'completed',
  'failed',
  'blocked',
  'cancelled',
] as const;

export type WorkflowAgentCallStatus = (typeof WORKFLOW_AGENT_CALL_STATUSES)[number];

/**
 * 脚本内一次 `agent()` 调用记录（计划 §5.5 + §11.3）。
 * `id` 为稳定 agentCallId：`hash(scriptHash + callPath + prompt + args + index)`，
 * 恢复时按 id 决定复用还是重跑。
 */
export interface WorkflowAgentCall {
  id: string;
  label?: string;
  prompt: string;
  model?: string;
  status: WorkflowAgentCallStatus;
  result?: unknown;
  error?: string;
  inputTokens: number;
  outputTokens: number;
  startedAt?: string;
  completedAt?: string;
  /**
   * 该调用结构化结果物化出的 Evidence id（计划 §11.3）。
   * Evidence id materialized from this call's structured result. Evidence 生成失败时
   * WorkflowRun 必须标记 failed，不得静默降级为普通文本总结。
   */
  evidenceId?: string;
  /**
   * 可选的 ThreadItem 关联；WorkflowAgentCall 独立于普通 ThreadItem，
   * 不保证存在 turnId / itemId。
   * Optional thread-item linkage; agent calls are independent of ordinary ThreadItems.
   */
  threadItemId?: string;
  /**
   * §14.5：结果内容指纹（sha256 前 16 位）与字节大小。大结果只向脚本暴露 ResultHandle，
   * 两者是审计与恢复复用的判据；全文仍落 `result`（服务端存储，不进入脚本主堆）。
   */
  resultHash?: string;
  resultSize?: number;
}

/** WorkflowRun 的持久化记录。 / Persisted record of one script workflow run. */
export interface WorkflowRunRecord {
  id: string;
  taskRunId: string;
  script: string;
  /** 批准后固化的脚本哈希；运行时不得变更，修改必须创建新的 request/run。 */
  scriptHash: string;
  args?: unknown;
  status: WorkflowRunStatus;
  agentCalls: WorkflowAgentCall[];
  usage: WorkflowUsage;
  startedAt: string;
  updatedAt: string;
  completedAt?: string;
  /**
   * P6：GoalRun 触发来源（goal 侧 TaskRun id）。缺省表示用户手动发起，不参与预算治理。
   * Originating goal TaskRun id; absent means user-initiated and exempt from goal budget.
   */
  goalRunId?: string;
  /**
   * P6：run 级 workflow 证据物化结果（`wev_<runId>_run`）。物化失败时 Run 必须标记 failed，
   * 不得在没有证据的情况下保持 completed（计划 §11.3 fail-fast）。
   */
  evidenceId?: string;
  /** P6：脚本 return 的终态结果（completed 时由服务层落库，供证据摘要与重建投影）。 */
  result?: unknown;
}

/**
 * Workflow 结果进入 Evidence 的承载形式（计划 §11.3）。
 * Evidence refs 保存 runId（+ agentCallId），GoalEvaluator 只消费 Evidence，不直接消费脚本变量。
 */
export type WorkflowEvidenceSource =
  | { kind: 'workflow_run'; runId: string }
  | { kind: 'workflow_agent_call'; runId: string; agentCallId: string };

/** WorkflowRun 状态迁移表（与 TaskRun 语义对齐）。 */
/** Workflow run transition table, aligned with TaskRun semantics. */
export const WORKFLOW_RUN_TRANSITIONS: Readonly<
  Record<WorkflowRunStatus, readonly WorkflowRunStatus[]>
> = {
  queued: ['running', 'blocked', 'cancelled', 'failed'],
  running: ['paused', 'blocked', 'cancelled', 'failed'],
  paused: ['running', 'cancelled', 'failed'],
  blocked: ['queued', 'cancelled', 'failed'],
  interrupted: ['running', 'queued', 'cancelled', 'failed'],
  completed: [],
  cancelled: [],
  failed: [],
};

export function canTransitionWorkflowRun(
  from: WorkflowRunStatus,
  to: WorkflowRunStatus,
): boolean {
  return WORKFLOW_RUN_TRANSITIONS[from].includes(to);
}

/**
 * 受限脚本的运行限制（计划 §5.4）。`maxTotalTokens` 用 0 表示不限（fail-open 例外），
 * 默认给 2_000_000 的合理上限。
 * Runtime limits of a restricted script; 0 means unlimited for maxTotalTokens, default is 2M.
 */
export interface WorkflowRuntimeLimits {
  maxConcurrentAgents: number;
  maxAgentsPerRun: number;
  maxItemsPerPipeline: number;
  maxTotalTokens: number;
  maxDurationMs: number;
  requireApproval: boolean;
}

/** 第一版默认运行限制（计划 §5.4 建议值）。 */
/** First-version defaults recommended by the plan. */
export const DEFAULT_WORKFLOW_RUNTIME_LIMITS: Readonly<WorkflowRuntimeLimits> = {
  maxConcurrentAgents: 4,
  maxAgentsPerRun: 50,
  maxItemsPerPipeline: 500,
  maxTotalTokens: 2_000_000,
  maxDurationMs: 30 * 60_000,
  requireApproval: true,
};

/**
 * GoalRun 触发 WorkflowRun 的显式请求（计划 §12.1）。
 * 不允许 GoalEvaluator 隐式触发；必须经 scriptValidator 静态校验 + 用户批准。
 */
export interface WorkflowScriptRequest {
  taskId: string;
  goalRunId: string;
  objective: string;
  proposedScript: string;
  estimatedAgents: number;
  estimatedTokens: number;
  limits: WorkflowRuntimeLimits;
}

/**
 * `GET /api/tasks/:id/goal-status` 的响应（计划 §13.1）。
 * evaluation 复用 types.ts 的 `GoalEvaluation`，不新增第二套评估载体（§14.1）。
 */
export interface TaskGoalStatusResponse {
  taskId: string;
  runId?: string;
  evaluation?: GoalEvaluation;
  passedCriteria: string[];
  failedCriteria: string[];
  blocker?: string;
  evidenceIds: string[];
}

// ─── 集中事件目录（计划 §14.9） ──────────────────────────────────────────────
// Centralized event catalog. Event names, payloads and ordering live here; every terminal
// state must emit a terminal event, and after an SSE disconnect the client may recover final
// state through the task query API.

export const TASK_EVENT_NAMES = [
  'task.created',
  'task.updated',
  'task.run.created',
  'task.run.updated',
  'task.run.terminal',
  'task.goal.evaluation.available',
  'task.plan.version.created',
  'task.user_input.required',
  'task.user_input.resolved',
  'workflow.request.created',
  'workflow.request.approved',
  'workflow.request.rejected',
  'workflow.run.created',
  'workflow.run.updated',
  'workflow.run.terminal',
  'workflow.agent_call.updated',
  'workflow.agent_call.terminal',
  'workflow.result.created',
  'workflow.evidence.created',
] as const;

export type TaskEventName = (typeof TASK_EVENT_NAMES)[number];

/** 终态事件集合；每个终态必须有对应事件。 / Terminal events, one per terminal outcome. */
export const TASK_TERMINAL_EVENT_NAMES: readonly TaskEventName[] = [
  'task.run.terminal',
  'workflow.run.terminal',
  'workflow.agent_call.terminal',
];

/** 判断任意字符串是否为已登记的任务/工作流事件名。 */
/** Whether an arbitrary string is a registered task/workflow event name. */
export function isTaskEventName(value: string): value is TaskEventName {
  return (TASK_EVENT_NAMES as readonly string[]).includes(value);
}

// ─── 错误码族 ────────────────────────────────────────────────────────────────
// Stable machine-readable error codes.

export const TASK_ERROR_CODES = [
  'TASK_NOT_FOUND',
  'TASK_INVALID_TRANSITION',
  'TASK_TERMINAL_STATE',
  'TASK_VERSION_CONFLICT',
  'TASK_ACTIVE_EXISTS',
  'TASK_RUN_NOT_FOUND',
  'TASK_PLAN_STEP_ID_CONFLICT',
  'TASK_PLAN_UNKNOWN_STEP_ID',
  'WORKFLOW_RUN_NOT_FOUND',
  'WORKFLOW_SCRIPT_INVALID',
  'WORKFLOW_APPROVAL_REQUIRED',
  'WORKFLOW_LIMIT_EXCEEDED',
  'WORKFLOW_EVIDENCE_MATERIALIZATION_FAILED',
] as const;

export type TaskErrorCode = (typeof TASK_ERROR_CODES)[number];

export interface TaskErrorDetails {
  from?: TaskRunStatusLike;
  to?: TaskRunStatusLike;
  actualVersion?: number;
  expectedVersion?: number;
  taskId?: string;
  runId?: string;
  workflowRunId?: string;
  stepId?: string;
  limit?: keyof WorkflowRuntimeLimits;
  [key: string]: unknown;
}

/** 迁移表与 Task 状态共用 `from`/`to` 描述，允许两类状态字符串。 */
type TaskRunStatusLike = TaskStatus | TaskRunState | WorkflowRunStatus | string;

/** 带稳定机器可读错误码的任务协议错误。 / Protocol error carrying a stable machine-readable code. */
export class TaskError extends Error {
  readonly code: TaskErrorCode;
  readonly details?: Readonly<TaskErrorDetails>;

  constructor(code: TaskErrorCode, message: string, details?: TaskErrorDetails) {
    super(message);
    this.name = 'TaskError';
    this.code = code;
    this.details = details;
  }
}

/**
 * 断言 TaskRun 迁移合法（计划 §11.4）。终态优先抛 TASK_TERMINAL_STATE，
 * 其余非法迁移抛 TASK_INVALID_TRANSITION。
 * Asserts a TaskRun transition; terminal sources report TASK_TERMINAL_STATE first.
 */
export function assertTaskRunTransition(from: TaskRunState, to: TaskRunState): void {
  if (isTaskRunTerminalState(from)) {
    throw new TaskError(
      'TASK_TERMINAL_STATE',
      `Task run in terminal state ${from} cannot transition to ${to}`,
      { from, to },
    );
  }
  if (!canTransitionTaskRun(from, to)) {
    throw new TaskError(
      'TASK_INVALID_TRANSITION',
      `Task run cannot transition from ${from} to ${to}`,
      { from, to },
    );
  }
}

/** 断言 Task 目标层迁移合法；终态优先抛 TASK_TERMINAL_STATE。 */
/** Asserts a Task status transition; terminal sources report TASK_TERMINAL_STATE first. */
export function assertTaskStatusTransition(from: TaskStatus, to: TaskStatus): void {
  if (isTaskTerminalState(from)) {
    throw new TaskError(
      'TASK_TERMINAL_STATE',
      `Task in terminal status ${from} cannot transition to ${to}`,
      { from, to },
    );
  }
  if (!canTransitionTaskStatus(from, to)) {
    throw new TaskError(
      'TASK_INVALID_TRANSITION',
      `Task cannot transition from ${from} to ${to}`,
      { from, to },
    );
  }
}

/**
 * API 层乐观锁版本校验。成功返回 true，冲突时抛 TASK_VERSION_CONFLICT。
 * Optimistic-lock check used by the API layer; throws TASK_VERSION_CONFLICT on mismatch.
 */
export function validateTaskVersion(actualVersion: number, expectedVersion: number): true {
  if (
    !Number.isSafeInteger(actualVersion) ||
    !Number.isSafeInteger(expectedVersion) ||
    actualVersion !== expectedVersion
  ) {
    throw new TaskError(
      'TASK_VERSION_CONFLICT',
      `Task version conflict: expected ${expectedVersion}, got ${actualVersion}`,
      { actualVersion, expectedVersion },
    );
  }
  return true;
}

export const assertTaskVersion = validateTaskVersion;

export function isTaskVersionMatch(actualVersion: number, expectedVersion: number): boolean {
  return (
    Number.isSafeInteger(actualVersion) &&
    Number.isSafeInteger(expectedVersion) &&
    actualVersion === expectedVersion
  );
}

// ─── Zod schemas ─────────────────────────────────────────────────────────────
// 稳定 JSON schema 契约；与 opsTask.ts 保持 strict + trim().min(1) 风格。
// Stable JSON-schema contracts; same strict + trim().min(1) style as opsTask.ts.

export const taskStatusSchema = z.enum(TASK_STATUSES);
export const taskRunStateSchema = z.enum(TASK_RUN_STATES);
export const taskRunKindSchema = z.enum(TASK_RUN_KINDS);
export const workflowKindSchema = z.enum(WORKFLOW_KINDS);
export const taskInteractionModeSchema = z.enum(TASK_INTERACTION_MODES);
export const taskOriginSchema = z.enum(TASK_ORIGINS);
export const taskStepStatusSchema = z.enum(TASK_STEP_STATUSES);
export const taskPlanTriggerSchema = z.enum(TASK_PLAN_TRIGGERS);
export const workflowRunStatusSchema = z.enum(WORKFLOW_RUN_STATUSES);
export const workflowAgentCallStatusSchema = z.enum(WORKFLOW_AGENT_CALL_STATUSES);
export const taskErrorCodeSchema = z.enum(TASK_ERROR_CODES);
export const taskEventNameSchema = z.enum(TASK_EVENT_NAMES);

const isoDateString = z.string().trim().min(1);
const idString = z.string().trim().min(1);
const idList = z.array(idString);
const nonNegativeInt = z.number().int().nonnegative();
const positiveInt = z.number().int().positive();

export const pendingUserInputSchema = z
  .object({
    question: z.string().trim().min(1),
    options: z.array(z.string().trim().min(1)).optional(),
    freeText: z.boolean(),
    askedAt: isoDateString,
  })
  .strict();

export const replanPolicySchema = z
  .object({
    maxReplansPerTask: nonNegativeInt,
    minIntervalMs: nonNegativeInt,
    triggerThreshold: positiveInt,
    tokenBudget: nonNegativeInt,
  })
  .strict();

export const goalBudgetPolicySchema = z
  .object({
    maxContinuations: nonNegativeInt,
    maxNoProgress: nonNegativeInt,
    maxWorkflowRunsPerGoal: nonNegativeInt,
    replan: replanPolicySchema,
  })
  .strict();

export const workflowRuntimeLimitsSchema = z
  .object({
    maxConcurrentAgents: positiveInt,
    maxAgentsPerRun: positiveInt,
    maxItemsPerPipeline: positiveInt,
    // 0 表示不限。/ 0 means unlimited.
    maxTotalTokens: nonNegativeInt,
    maxDurationMs: positiveInt,
    requireApproval: z.boolean(),
  })
  .strict();

export const taskStepSchema = z
  .object({
    id: idString,
    description: z.string().trim().min(1),
    status: taskStepStatusSchema,
    evidenceIds: idList,
    dependsOn: z.array(idString).optional(),
    failureReason: z.string().optional(),
    startedAt: isoDateString.optional(),
    completedAt: isoDateString.optional(),
  })
  .strict();

export const taskPlanVersionSchema = z
  .object({
    version: nonNegativeInt,
    createdAt: isoDateString,
    trigger: taskPlanTriggerSchema,
    steps: z.array(taskStepSchema),
  })
  .strict();

export const taskSchema: z.ZodType<Task> = z
  .object({
    id: idString,
    threadId: idString,
    objective: z.string().trim().min(1),
    acceptanceCriteria: z.array(z.string().trim().min(1)),
    status: taskStatusSchema,
    currentRunId: idString.optional(),
    runIds: idList,
    latestPlan: taskPlanVersionSchema.optional(),
    evidenceIds: idList,
    createdAt: isoDateString,
    updatedAt: isoDateString,
    completedAt: isoDateString.optional(),
    pendingInput: pendingUserInputSchema.optional(),
    version: nonNegativeInt,
    interactionMode: taskInteractionModeSchema.optional(),
    origin: taskOriginSchema.optional(),
  })
  .strict();

export const taskRunSchema: z.ZodType<TaskRun> = z
  .object({
    id: idString,
    taskId: idString,
    threadId: idString,
    kind: taskRunKindSchema,
    status: taskRunStateSchema,
    harnessRunId: idString.optional(),
    workflowRunId: idString.optional(),
    workflowKind: workflowKindSchema.optional(),
    startedAt: isoDateString.optional(),
    updatedAt: isoDateString,
    completedAt: isoDateString.optional(),
    error: z.string().optional(),
    checkpointId: idString.optional(),
    version: nonNegativeInt,
  })
  .strict();

export const workflowUsageSchema = z
  .object({
    inputTokens: nonNegativeInt,
    outputTokens: nonNegativeInt,
    agentCallCount: nonNegativeInt,
    durationMs: nonNegativeInt,
  })
  .strict();

export const workflowAgentCallSchema: z.ZodType<WorkflowAgentCall> = z
  .object({
    id: idString,
    label: z.string().trim().min(1).optional(),
    prompt: z.string().trim().min(1),
    model: z.string().trim().min(1).optional(),
    status: workflowAgentCallStatusSchema,
    result: z.unknown(),
    error: z.string().optional(),
    inputTokens: nonNegativeInt,
    outputTokens: nonNegativeInt,
    startedAt: isoDateString.optional(),
    completedAt: isoDateString.optional(),
    evidenceId: idString.optional(),
    threadItemId: idString.optional(),
    resultHash: z.string().trim().min(1).optional(),
    resultSize: nonNegativeInt.optional(),
  })
  .strict();

export const workflowEvidenceSourceSchema: z.ZodType<WorkflowEvidenceSource> = z.union([
  z.object({ kind: z.literal('workflow_run'), runId: idString }).strict(),
  z
    .object({ kind: z.literal('workflow_agent_call'), runId: idString, agentCallId: idString })
    .strict(),
]);

export const workflowRunRecordSchema: z.ZodType<WorkflowRunRecord> = z
  .object({
    id: idString,
    taskRunId: idString,
    script: z.string().min(1),
    scriptHash: idString,
    args: z.unknown(),
    status: workflowRunStatusSchema,
    agentCalls: z.array(workflowAgentCallSchema),
    usage: workflowUsageSchema,
    startedAt: isoDateString,
    updatedAt: isoDateString,
    completedAt: isoDateString.optional(),
    goalRunId: idString.optional(),
    evidenceId: idString.optional(),
    result: z.unknown(),
  })
  .strict();

export const workflowScriptRequestSchema: z.ZodType<WorkflowScriptRequest> = z
  .object({
    taskId: idString,
    goalRunId: idString,
    objective: z.string().trim().min(1),
    proposedScript: z.string().min(1),
    estimatedAgents: nonNegativeInt,
    estimatedTokens: nonNegativeInt,
    limits: workflowRuntimeLimitsSchema,
  })
  .strict();

// evaluation 复用 types.ts 的 GoalEvaluation；protocol 已在 schemas.ts 提供 goalEvaluationSchema，
// 但本文件不允许 import 除 zod 与 ./types.js 之外的模块，因此这里以 z.unknown() 承载、
// 接口层用 GoalEvaluation 强类型约束。
// The `evaluation` payload is typed as GoalEvaluation but validated as unknown here, because this
// module may only import zod and ./types.js; consumers should validate with goalEvaluationSchema.
export const taskGoalStatusResponseSchema = z
  .object({
    taskId: idString,
    runId: idString.optional(),
    evaluation: z.unknown().optional(),
    passedCriteria: z.array(z.string().trim().min(1)),
    failedCriteria: z.array(z.string().trim().min(1)),
    blocker: z.string().optional(),
    evidenceIds: idList,
  })
  .strict();

export const taskTransitionEventSchema = z
  .object({
    event: taskEventNameSchema,
    taskId: idString,
    threadId: idString,
    runId: idString.optional(),
    from: z.string().trim().min(1).optional(),
    to: z.string().trim().min(1).optional(),
    version: nonNegativeInt.optional(),
    occurredAt: isoDateString,
    reason: z.string().optional(),
  })
  .strict();
