// 任务中心局部样式常量：只在此目录内以 React 内联 style + CSS 变量表达，
// 不改动全局 styles.css（AGENTS.md §7：1px 低对比边框、靠间距/分隔线分层、无渐变/毛玻璃/大阴影）。
// — Chinese: local inline style constants; never touches the global stylesheet.

import type { CSSProperties } from 'react';
import type { StatusTone } from '../../features/tasks/taskCenterModel.js';

/** tone → 语义色变量：仅用于文字/小圆点/低对比左边框，不作大面积背景。 */
export const toneColor: Record<StatusTone, string> = {
  neutral: 'var(--nx-muted)',
  active: 'var(--nx-blue)',
  warning: 'var(--nx-warn)',
  success: 'var(--nx-green)',
  danger: 'var(--nx-danger)',
};

/** tone → 徽章淡背景（沿用现有 *-soft 变量，对比克制）。 */
export const toneSoftBg: Record<StatusTone, string> = {
  neutral: 'transparent',
  active: 'var(--nx-blue-soft)',
  warning: 'transparent',
  success: 'var(--nx-green-soft)',
  danger: 'transparent',
};

export const styles: Record<string, CSSProperties> = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
    minHeight: 0,
    background: 'var(--nx-panel)',
    color: 'var(--nx-text)',
    fontSize: 13,
    lineHeight: 1.5,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 14px',
    borderBottom: '1px solid var(--nx-border)',
    flex: '0 0 auto',
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--nx-text)',
    margin: 0,
  },
  headerCount: {
    fontSize: 12,
    color: 'var(--nx-muted)',
  },
  createButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    border: '1px solid var(--nx-border)',
    borderRadius: 6,
    background: 'transparent',
    color: 'var(--nx-text)',
    padding: '3px 8px',
    font: 'inherit',
    fontSize: 11,
    cursor: 'pointer',
  },
  spacer: { flex: '1 1 auto' },
  iconButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 26,
    height: 26,
    padding: 0,
    border: '1px solid transparent',
    borderRadius: 6,
    background: 'transparent',
    color: 'var(--nx-muted)',
    cursor: 'pointer',
  },
  body: {
    display: 'flex',
    flex: '1 1 auto',
    minHeight: 0,
    overflow: 'hidden',
  },
  // 运行观察固定在窄右栏，列表和详情纵向排布，避免出现粗重的二栏大弹窗感。
  observerRoot: {
    background: 'transparent',
  },
  observerBody: {
    display: 'flex',
    flexDirection: 'column',
    flex: '1 1 auto',
    minHeight: 0,
    overflow: 'hidden',
    gap: 8,
  },
  observerListPane: {
    display: 'flex',
    flexDirection: 'column',
    flex: '0 0 auto',
    maxHeight: '38%',
    minWidth: 0,
    borderRight: 'none',
    borderBottom: '1px solid var(--nx-border)',
    background: 'transparent',
  },
  observerDetailPane: {
    display: 'flex',
    flexDirection: 'column',
    flex: '1 1 auto',
    minWidth: 0,
    minHeight: 0,
  },
  listPane: {
    display: 'flex',
    flexDirection: 'column',
    flex: '0 0 260px',
    minWidth: 0,
    borderRight: '1px solid var(--nx-border)',
    background: 'var(--nx-sidebar)',
  },
  listScroll: {
    flex: '1 1 auto',
    minHeight: 0,
    overflowY: 'auto',
    padding: '6px 0',
  },
  detailPane: {
    display: 'flex',
    flexDirection: 'column',
    flex: '1 1 auto',
    minWidth: 0,
  },
  detailScroll: {
    flex: '1 1 auto',
    minHeight: 0,
    overflowY: 'auto',
    padding: '14px 16px',
  },
  listItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    width: '100%',
    padding: '8px 14px',
    border: 'none',
    borderLeft: '2px solid transparent',
    background: 'transparent',
    color: 'inherit',
    textAlign: 'left',
    cursor: 'pointer',
    font: 'inherit',
  },
  listItemActive: {
    background: 'var(--nx-card)',
    borderLeftColor: 'var(--nx-blue)',
  },
  listItemTitle: {
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--nx-text)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  listItemMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 11,
    color: 'var(--nx-muted)',
  },
  rowBetween: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    padding: '1px 7px',
    borderRadius: 5,
    border: '1px solid var(--nx-border)',
    fontSize: 11,
    lineHeight: 1.6,
    whiteSpace: 'nowrap',
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    flex: '0 0 auto',
  },
  section: {
    paddingTop: 12,
    marginTop: 12,
    borderTop: '1px solid var(--nx-border)',
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--nx-muted)',
    margin: '0 0 8px',
  },
  objective: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--nx-text)',
    margin: '0 0 6px',
    lineHeight: 1.45,
  },
  muted: {
    color: 'var(--nx-muted)',
  },
  faint: {
    color: 'var(--nx-faint)',
  },
  time: {
    fontSize: 11,
    color: 'var(--nx-faint)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  criteriaItem: {
    display: 'flex',
    gap: 6,
    fontSize: 12.5,
    color: 'var(--nx-text)',
    padding: '2px 0',
  },
  stepRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    padding: '6px 0',
  },
  stepIndex: {
    flex: '0 0 auto',
    width: 18,
    fontSize: 11,
    color: 'var(--nx-faint)',
    textAlign: 'right',
  },
  stepBody: {
    flex: '1 1 auto',
    minWidth: 0,
  },
  stepDesc: {
    fontSize: 12.5,
    color: 'var(--nx-text)',
    wordBreak: 'break-word',
  },
  stepHint: {
    fontSize: 11,
    marginTop: 2,
  },
  listReset: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  empty: {
    padding: '20px 14px',
    color: 'var(--nx-muted)',
    fontSize: 12.5,
    textAlign: 'center',
  },
  error: {
    margin: '6px 14px',
    padding: '8px 10px',
    border: '1px solid var(--nx-border)',
    borderLeftColor: 'var(--nx-danger)',
    borderLeftWidth: '2px',
    borderRadius: 6,
    fontSize: 12,
    color: 'var(--nx-text)',
    background: 'var(--nx-soft)',
  },
  pendingCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    padding: '10px 12px',
    border: '1px solid var(--nx-border)',
    borderLeftColor: 'var(--nx-warn)',
    borderLeftWidth: '2px',
    borderRadius: 6,
    background: 'var(--nx-soft)',
  },
  pendingHead: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--nx-warn)',
  },
  pendingQuestion: {
    fontSize: 13,
    color: 'var(--nx-text)',
    wordBreak: 'break-word',
  },
  chipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
  },
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '1px 7px',
    border: '1px solid var(--nx-border)',
    borderRadius: 5,
    fontSize: 11,
    color: 'var(--nx-muted)',
    maxWidth: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  statRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 14,
    fontSize: 12,
    color: 'var(--nx-muted)',
  },
  statValue: {
    fontSize: 15,
    fontWeight: 600,
    color: 'var(--nx-text)',
    marginRight: 4,
  },
  linkButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
    padding: '2px 6px',
    border: '1px solid var(--nx-border)',
    borderRadius: 6,
    background: 'transparent',
    color: 'var(--nx-muted)',
    fontSize: 11.5,
    cursor: 'pointer',
    font: 'inherit',
  },
  runRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '6px 0',
    borderTop: '1px solid var(--nx-border)',
  },
  // 底部操作区：靠右、就近（不在页面标题区）；按钮 1px 低对比边框，hover/focus 不加粗描边。
  actionBar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 14,
    paddingTop: 12,
    borderTop: '1px solid var(--nx-border)',
  },
  actionButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '4px 12px',
    border: '1px solid var(--nx-border)',
    borderRadius: 6,
    background: 'transparent',
    color: 'var(--nx-text)',
    fontSize: 12.5,
    lineHeight: 1.5,
    cursor: 'pointer',
    font: 'inherit',
    whiteSpace: 'nowrap',
  },
  actionButtonDanger: {
    color: 'var(--nx-danger)',
  },
  actionButtonBusy: {
    opacity: 0.55,
    cursor: 'default',
  },
  // 行内错误条：局部、短时、左缘语义色，不做大红框。
  inlineError: {
    marginTop: 8,
    padding: '6px 10px',
    border: '1px solid var(--nx-border)',
    borderLeftColor: 'var(--nx-warn)',
    borderLeftWidth: '2px',
    borderRadius: 6,
    fontSize: 12,
    color: 'var(--nx-text)',
    background: 'var(--nx-soft)',
  },
  // 转向行内输入区：展开后在操作条下方占满一行。
  redirectRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    width: '100%',
  },
  textInput: {
    flex: '1 1 200px',
    minWidth: 0,
    padding: '5px 8px',
    border: '1px solid var(--nx-border)',
    borderRadius: 6,
    background: 'var(--nx-panel)',
    color: 'var(--nx-text)',
    fontSize: 12.5,
    font: 'inherit',
  },
  // 待补充回答区：单选 + 自由文本 + 提交。
  answerRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  radioRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 12.5,
    color: 'var(--nx-text)',
    cursor: 'pointer',
  },
};
